version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  # jobs:
  #   pre_install:
  #     - bash ./docs/scripts/pre_install.sh


conda:
  environment: environment.yml

# Equivalent to `pip install .[docs]`
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
      # Install with no dependencies
      # no_deps: true

  # install:
  #   - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true
