version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - bash ./docs/scripts/pre_install.sh

# Equivalent to `pip install .[docs]`
python:
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt
  #     extra_requirements:
  #       - docs
  # install:
      

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true
